import { Note } from "./notesTypes";

export const data: Note[] = [
  {
    id: "123-abc",
    title: "Exploration Ideas",
    text: "Exploration Ideas is a collection of innovative concepts and creative sparks that have the potential to reshape the way we think and perceive the world. It encompasses a diverse range of subjects, from cutting-edge technology to avant-garde art. The exploration of these ideas aims to push the boundaries of conventional thinking and inspire new possibilities for the future. It's a journey into the unknown, where curiosity and imagination converge to create something truly extraordinary.",
    tags: ["Personal", "To-do"],
    created_at: "01-01-2023 10:15",
    updated_at: "01-01-2023 12:30",
  },
  {
    id: "234-abc",
    title: "Database Systems Week 4",
    text: "In Database Systems Week 4, we delve deep into the intricate realm of database management. This week's study materials cover a wide array of topics, including advanced query optimization, database normalization techniques, and the implementation of transaction control. As we navigate through the complexities of database systems, the goal is to gain a profound understanding of the foundational principles that underpin effective data organization and retrieval. Each lesson is a step forward in mastering the art and science of managing databases efficiently.",
    tags: ["Study"],
    created_at: "04-12-2023 08:45",
    updated_at: "04-12-2023 14:18",
  },
  {
    id: "345-abc",
    title: "Grocery List",
    text: "The Grocery List is a curated compilation of essential items needed for the week's culinary adventures. From fresh produce to pantry staples, this meticulously planned list ensures that every meal is a delightful and well-balanced experience. It includes a variety of ingredients, both everyday necessities and special treats, guaranteeing a seamless and enjoyable shopping experience. Whether it's checking off the to-do list or selecting important items, the Grocery List is the key to a well-stocked and organized kitchen.",
    tags: ["To-do", "Important"],
    created_at: "04-19-2023 15:22",
    updated_at: "04-20-2023 09:45",
  },
  {
    id: "456-abc",
    title: "Morning Yoga Routine",
    text: "The Morning Yoga Routine is a rejuvenating sequence designed to kickstart the day with positivity and energy. Each yoga pose is carefully selected to promote flexibility, balance, and mindfulness. Whether you're a seasoned yogi or a beginner, this routine caters to all levels of experience. From sun salutations to deep stretches, it's a holistic practice that contributes to physical well-being and mental clarity. Embrace the serenity of the morning and embark on a journey of self-care with this invigorating yoga routine.",
    tags: ["Personal", "Important"],
    created_at: "05-05-2023 23:03",
    updated_at: "05-06-2023 01:20",
  },
  {
    id: "567-abc",
    title: "Summer Reading List",
    text: "The Summer Reading List features a curated selection of books that promise to transport readers to captivating worlds and thought-provoking narratives. From gripping novels to insightful non-fiction, this list caters to diverse literary tastes. Whether you're lounging by the beach or enjoying a quiet afternoon at home, these books offer a perfect escape into the realms of imagination and knowledge. Explore new stories, gain new perspectives, and let the magic of literature enrich your summer days.",
    tags: ["Personal", "To-do"],
    created_at: "06-15-2023 12:30",
    updated_at: "06-15-2023 18:45",
  },
  {
    id: "678-abc",
    title: "Project Proposal",
    text: "The Project Proposal outlines a comprehensive plan for the upcoming venture, detailing objectives, timelines, and key milestones. It serves as a roadmap for success, providing a clear vision for the project team. From project scope to resource allocation, every aspect is meticulously defined to ensure effective execution. This proposal acts as a guide for stakeholders, aligning expectations and fostering collaboration. With strategic planning and a detailed approach, the project is poised for success from initiation to completion.",
    tags: ["Important"],
    created_at: "07-10-2023 09:15",
    updated_at: "07-10-2023 16:42",
  },
  {
    id: "789-abc",
    title: "Travel Bucket List",
    text: "The Travel Bucket List is a compilation of dream destinations and must-visit places around the world. From exotic beaches to historic landmarks, each entry sparks a sense of wanderlust and adventure. Whether you're an avid traveler or someone seeking inspiration for future journeys, this list is a visual feast of breathtaking landscapes and cultural experiences. Embark on a virtual journey, explore diverse cultures, and let the Travel Bucket List inspire your next unforgettable adventure.",
    tags: ["To-do"],
    created_at: "08-22-2023 14:10",
    updated_at: "08-23-2023 09:28",
  },
  {
    id: "890-abc",
    title: "Coding Challenge Solutions",
    text: "Coding Challenge Solutions documents the step-by-step process of solving complex programming puzzles and challenges. From algorithmic problem-solving to code optimization, each solution is a testament to problem-solving skills and coding proficiency. Whether you're a coding enthusiast or a professional developer, these solutions provide valuable insights and learning opportunities. Dive into the world of code, unravel the intricacies of challenges, and enhance your programming skills with this comprehensive collection of solutions.",
    tags: ["Study", "Important"],
    created_at: "09-30-2023 11:55",
    updated_at: "09-30-2023 15:40",
  },
  {
    id: "901-abc",
    title: "Digital Art Gallery",
    text: "The Digital Art Gallery showcases a mesmerizing collection of digital artworks from talented artists around the world. From digital paintings to interactive installations, each piece represents a fusion of creativity and technology. Explore the boundaries of digital expression, immerse yourself in vibrant visuals, and experience the convergence of art and innovation. This gallery is a celebration of the limitless possibilities that digital art offers, inspiring both artists and enthusiasts to explore the digital realm of artistic expression.",
    tags: ["Personal"],
    created_at: "11-05-2023 08:45",
    updated_at: "11-05-2023 12:15",
  },
];
